# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Home
      title: This is the first menu item.
      path: homepage
      class: first
    - label: All pages
      path: pages/
    - label: All entries
      path: entries/
    - label: Archive
      path: page/archive
